'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const get=path=>fs.readFileSync(path,'utf8');
const html=get('rates.html');
const guided=get('assets/rates-easy-journey.js');
const style=get('assets/rates-easy-journey.css');
const apply=get('assets/store-applications.js');
const applyStyle=get('assets/store-applications.css');
for(const [name,src] of [['guided journey',guided],['secure application',apply]]){
 new vm.Script(src,{filename:name});
}
assert.match(html,/id="mobile-easy-intro"/);
assert.match(html,/id="mobile-easy-advanced"/);
assert.match(html,/id="mobile-easy-result-guide"/);
assert.match(html,/id="mobile-easy-see-results"/);
assert.match(html,/data-purpose-category="senior"/);
assert.match(html,/data-purpose-category="kids"/);
assert.match(html,/data-purpose-category="value"/);
assert.match(html,/data-purpose-category="premium"/);
assert.match(html,/id="senior-phone-kind"/);
assert.match(html,/data-senior-type="smartphone"/);
assert.match(html,/data-senior-type="folder"/);
assert.match(guided,/function filterSeniorCards/);
assert.match(guided,/function folderName/);
const start=guided.indexOf('  function folderName(value){');
const end=guided.indexOf('  function visibleSeniorCards()',start);
assert.ok(start>0&&end>start,'senior folder classifier present');
const classification={};
vm.runInNewContext(guided.slice(start,end)+';globalResult=folderName;',classification);
assert.equal(classification.globalResult('스타일폴더2'),true,'button folder phones recognized');
assert.equal(classification.globalResult('STYLE FOLDER 2'),true,'English folder name recognized');
assert.equal(classification.globalResult('갤럭시 A17'),false,'regular Galaxy smartphone remains visible');
assert.equal(classification.globalResult('갤럭시 Z 폴드8'),false,'modern foldable smartphone is not a button phone');
assert.equal(classification.globalResult('iPhone 18'),false,'iPhone remains in smart recommendations');

assert.match(guided,/\.style\.display=show\?\x27\x27:\x27none\x27/);
assert.match(style,/\.senior-phone-kind-btn/);
assert.match(guided,/purpose-carrier/);
assert.match(guided,/purpose-join/);
assert.match(guided,/scrollToResult/);
assert.match(style,/min-height:55px/);
assert.match(html,/store-application-easy-heading/);
assert.match(html,/store-inquiry-optional/);
assert.match(html,/id="store-application-fallback"/);
assert.match(apply,/category:'mobile'/);
assert.match(apply,/card\.dataset\.deviceId/);
assert.match(apply,/card\.dataset\.selectedMethod/);
assert.match(apply,/function revealInternetStep/);
assert.match(apply,/function showApplicationFallback/);
assert.match(applyStyle,/font-size:17px/);
assert.match(html,/store-applications\.js\?v=20261008-easy5/);
assert.match(html,/rates-easy-journey\.js\?v=20261008-senior3/);
assert.match(html,/rates-easy-journey\.css\?v=20261008-senior3/);
console.log('Phone easy journey: structure, script syntax, handoff and accessible form hooks passed.');
