import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {createIntakeHandlers} from '../src/intake.js';
import {INTAKE_READY} from '../src/intake-readiness.js';
assert.equal(INTAKE_READY,false,'Collection must remain closed until compliance review is complete');
await assert.rejects(()=>createIntakeHandlers({httpError:(status,message)=>Object.assign(new Error(message),{status})}).submit({},{}),e=>e.status===423);
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const bundle=async path=>(await build({entryPoints:[fileURLToPath(new URL(path,import.meta.url))],bundle:true,write:false,format:'esm',external:['cloudflare:*'],plugins:[{name:'local-intake-ready-fixture',setup(b){b.onLoad({filter:/intake-readiness\.js$/},async({path})=>({contents:(await readFile(path,'utf8')).replace('INTAKE_READY = false','INTAKE_READY = true'),loader:'js'}));}}]})).outputFiles[0].text;
const script=await bundle('../src/worker.js'),gateway=await bundle('../src/consent-public.js');
const schema=await readFile(new URL('../migrations/0001_init.sql',import.meta.url),'utf8');
const mf=new Miniflare(convertV4MiniflareOptions({workers:[
 {name:'crm',routes:['crm.test/*'],modules:true,script,compatibilityDate:'2026-09-01',d1Databases:['DB'],bindings:{DEV_AUTH_BYPASS:'1',ALLOWED_ADMIN_EMAILS:'admin@example.invalid',SMS_MODE:'dry_run',CRM_DATA_KEY_B64:Buffer.alloc(32,7).toString('base64'),CRM_HMAC_KEY_B64:Buffer.alloc(32,9).toString('base64')}},
 {name:'public',routes:['consent.test/*'],modules:true,script:gateway,compatibilityDate:'2026-09-01',serviceBindings:{CONSENT:{name:'crm',entrypoint:'ConsentPublic'}},ratelimits:{INTAKE_LIMITER:{namespace_id:'1001',simple:{limit:100,period:60}}},assets:{directory:fileURLToPath(new URL('../consent-web/',import.meta.url)),binding:'ASSETS',run_worker_first:true}}
]}));
const headers={'X-CRM-Dev-Email':'admin@example.invalid','content-type':'application/json',origin:'https://crm.test'};
const admin=(path,body)=>mf.dispatchFetch('https://crm.test/api/'+path,{headers,method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})});
const submit=(body,origin='https://consent.test')=>mf.dispatchFetch('https://consent.test/api/intake',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(body)});
try{
 const db=await mf.getD1Database('DB','crm');
 for(const sql of schema.split(';').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();
 assert.equal((await admin('health')).status,200);
 const home=await mf.dispatchFetch('https://consent.test/',{redirect:'manual'});
 assert.equal(home.status,200);assert.match(await home.text(),/name-pad/);
 assert.match(home.headers.get('content-security-policy'),/manifest-src 'self'/);
 assert.equal((await mf.dispatchFetch('https://consent.test/intake.js')).status,200);
 assert.equal((await mf.dispatchFetch('https://consent.test/handwriting.js')).status,200);
 assert.equal((await mf.dispatchFetch('https://consent.test/manifest.webmanifest')).status,200);
 assert.equal((await mf.dispatchFetch('https://consent.test/api/customers')).status,404);
 assert.equal((await mf.dispatchFetch('https://crm.test/api/consent-intakes')).status,401);
 const form=await (await mf.dispatchFetch('https://consent.test/api/intake-form')).json();
 assert.equal(form.enabled,true);
 assert.equal((await mf.dispatchFetch('https://consent.test/privacy')).status,200);
 assert.match(form.policy.items,/손글씨 이름, 손글씨 서명/);
 const phone=['010','0000','0001'].join('');
 const choices={customer_care:false,marketing_use:true,ad_sms:true,ad_kakao:false,ad_call:false};
 const ink=[[[0.1,0.2],[0.3,0.4],[0.5,0.2],[0.7,0.5]]];
 const body={handwriting_name:ink,signature:ink,customer_confirmed:true,request_id:crypto.randomUUID(),form_hash:form.form_hash,name:'가상고객',phone,choices,adult_confirmed:true};
 assert.equal((await submit(body,'https://evil.invalid')).status,403);
 assert.equal((await submit({...body,phone:'123'})).status,400);
 assert.equal((await submit({...body,adult_confirmed:false})).status,400);
 assert.equal((await submit({...body,customer_confirmed:false})).status,400);
 for(const invalid of [null,[],[[[0.2,0.2],[0.2,0.2],[0.2,0.2],[0.2,0.2]]],[[[2,0],[0,0],[0,1],[1,1]]],[Array.from({length:2501},(_,i)=>[i%2,0.5])]]){
  assert.equal((await submit({...body,signature:invalid})).status,400);
  assert.equal((await submit({...body,handwriting_name:invalid})).status,400);
 }
 assert.equal((await submit({...body,form_hash:'stale'})).status,409);
 const refuse={...body,choices:Object.fromEntries(Object.keys(choices).map(k=>[k,false]))};
 assert.deepEqual(await (await submit(refuse)).json(),{ok:true,saved:false});
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consent_intakes').first()).n,0);
 assert.equal((await submit(body)).status,200);
 assert.equal((await submit(body)).status,200);
 assert.equal((await submit({...body,signature:[[[0.2,0.2],[0.3,0.4],[0.5,0.2],[0.7,0.5]]]})).status,409);
 let raw=await db.prepare('SELECT * FROM consent_intakes').first();
 assert.ok(!raw.payload_enc.includes(body.name)&&!raw.payload_enc.includes(phone));
 assert.ok(!JSON.stringify(raw).includes(phone));
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consent_intakes').first()).n,1);
 let list=await (await admin('consent-intakes')).json();
 assert.equal(list.items[0].name,'');assert.equal(list.items[0].has_handwriting,true);assert.equal(list.items[0].signature,undefined);assert.equal(list.items[0].match,'new');assert.equal(list.items[0].status,'pending');
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consents').first()).n,0);
 const inkPath='consent-intakes/'+body.request_id+'/handwriting';
 assert.equal((await mf.dispatchFetch('https://crm.test/api/'+inkPath)).status,401);
 assert.equal((await mf.dispatchFetch('https://consent.test/api/'+inkPath)).status,404);
 assert.deepEqual((await (await admin(inkPath)).json()).signature,ink);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/review',{confirmed:true,name:body.name})).status,400);
 await admin('import',{rows:[{name:body.name,phone,carrier:'KT',opened_on:'2024-09-01'}]});
 list=await (await admin('consent-intakes')).json();assert.equal(list.items[0].match,'phone_only');
 assert.equal((await admin('consent-intakes/'+body.request_id+'/review',{confirmed:true,name:body.name,handwriting_checked:true})).status,200);
 list=await (await admin('consent-intakes')).json();assert.equal(list.items[0].status,'confirmed');assert.ok(list.items[0].customer_id);
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consents').first()).n,0);
 const receipt=await (await submit(body)).json();assert.equal(receipt.receipt.captured_at,raw.captured_at);assert.equal(receipt.receipt.choices.ad_sms,true);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/notice',{confirmed:true,target:'initial',method:'sms'})).status,200);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/notice',{confirmed:true,target:'initial',method:'sms'})).status,200);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/notice',{confirmed:true,target:'periodic',method:'phone'})).status,400);
 const care={...body,request_id:crypto.randomUUID(),choices:{customer_care:true,marketing_use:false,ad_sms:false,ad_kakao:false,ad_call:false}};
 assert.equal((await submit(care)).status,200);await admin('consent-intakes/'+care.request_id+'/remove',{confirmed:true});
 assert.equal((await submit({...care,request_id:crypto.randomUUID(),choices:{...care.choices,ad_sms:true}})).status,400);
 const spoof={...body,request_id:crypto.randomUUID(),name:'다른이름'};
 assert.equal((await submit(spoof)).status,200);
 assert.equal((await admin('consent-intakes/'+spoof.request_id+'/review',{confirmed:true,name:'다른이름',handwriting_checked:true})).status,409);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/channel',{confirmed:true,channel:'ad_sms'})).status,200);
 list=await (await admin('consent-intakes')).json();
 assert.ok(list.items.every(i=>i.effective_choices.ad_sms===false));
 assert.ok(list.items.every(i=>i.choices.ad_sms===true),'Original evidence must not change');
 const action=list.items.find(i=>i.id===body.request_id).actions.find(a=>a.kind==='channel_withdrawal');
 assert.equal((await admin('consent-intakes/'+body.request_id+'/notice',{confirmed:true,target:action.id,method:'in_person'})).status,200);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/channel',{confirmed:true,channel:'marketing_use'})).status,400);
 assert.equal((await admin('consent-intakes/'+spoof.request_id+'/remove',{confirmed:true})).status,200);
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consent_intakes').first()).n,1);
 assert.equal((await admin('consent-intakes/'+body.request_id+'/remove',{confirmed:true,withdraw:true,notice_confirmed:true})).status,200);
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consent_intakes').first()).n,0);
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consent_intake_actions').first()).n,0);
 const latest=await db.prepare("SELECT status FROM consents WHERE purpose='ad_sms' ORDER BY rowid DESC LIMIT 1").first();assert.equal(latest.status,'revoked');
 const expire={...body,request_id:crypto.randomUUID()};await submit(expire);
 await db.prepare("UPDATE consent_intakes SET expires_at='2000-01-01'").run();
 assert.equal((await (await admin('consent-intakes')).json()).items.length,0);
 assert.equal((await db.prepare('SELECT COUNT(*) n FROM consent_intakes').first()).n,0);
 const big=await mf.dispatchFetch('https://consent.test/api/intake',{method:'POST',headers:{'content-type':'application/json',origin:'https://consent.test'},body:'x'.repeat(131073)});
 assert.equal(big.status,413);
 // A pre-handwriting intake keeps its original typed name and can still be reviewed.
 const legacyId=crypto.randomUUID(),key=await crypto.subtle.importKey('raw',Buffer.alloc(32,7),'AES-GCM',false,['encrypt']);
 const iv=crypto.getRandomValues(new Uint8Array(12));
 const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify({name:body.name,phone,choices,adult_confirmed:true})));
 const encrypted=Buffer.from(iv).toString('base64')+'.'+Buffer.from(cipher).toString('base64');
 await db.prepare('INSERT INTO consent_intakes(id,payload_enc,phone_hmac,form_hash,form_json,captured_at,expires_at) VALUES(?,?,?,?,?,?,?)').bind(legacyId,encrypted,raw.phone_hmac,'legacy',JSON.stringify({version:'legacy'}),new Date().toISOString(),'2099-01-01').run();
 list=await (await admin('consent-intakes')).json();assert.equal(list.items[0].name,body.name);assert.equal(list.items[0].has_handwriting,false);
 assert.equal((await admin('consent-intakes/'+legacyId+'/review',{confirmed:true})).status,200);
 list=await (await admin('consent-intakes')).json();assert.equal(list.items[0].name,body.name);assert.equal(list.items[0].status,'confirmed');
 console.log('Consent compliance: release gate, assets, care/marketing separation, encrypted evidence, notice records, channel withdrawal, legacy review and cascading deletion passed');
}finally{await mf.dispose();}
